services:
  server:
    build:
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - PYCOOKIE_URL=${PYCOOKIE_URL}
      - PYCOOKIE_SECRET=${PYCOOKIE_SECRET}
      - PYCOOKIE_PASsSWORD=${PYCOOKIE_PASSWORD}
      - PYCOOKIE_USER=${PYCOOKIE_USER}
      - WEBDRIVER_POLL_TIMEOUT=${WEBDRIVER_POLL_TIMEOUT}
      - OUTPUT_DIR=${OUTPUT_DIR}
