name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        # You may pin to the exact commit or the version.
        # uses: SpicyPizza/create-envfile@1e127125f92644a19b9230964f24ee8c5955b73b
        uses: SpicyPizza/create-envfile@1e127125f92644a19b9230964f24ee8c5955b73b
        with:
          # The filename for the envfile
          file_name: .env
          envkey_DEBUG: false
      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm
        
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ secrets.DOCKER_REGISTRY }}
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
